// Calibration table for the size estimator.
//
// REGENERATED by the offline fitter (npm run fit:calibration, sizelab/fit/).
// HYBRID fit: base, slotStreamCost and the Shrinkler ratios are MEASURED from
// the corpus; per-op opCost keeps the source-grounded tiered seeds (the corpus
// can't separate per-op routine from base — collinear — so a raw per-op
// regression is degenerate). Types live in ./calibration-types.
import type { CalibrationData } from './calibration-types';

export type { CalibrationData, ShrinkModel, FitQuality } from './calibration-types';

export const CALIBRATION: CalibrationData = {
  base: 13437,
  slotStreamCost: 96,
  opCost: {
    1: 48,
    2: 64,
    3: 80,
    4: 128,
    5: 80,
    6: 80,
    7: 112,
    8: 120,
    9: 32,
    10: 32,
    11: 112,
    12: 160,
    13: 320,
    14: 32,
    15: 320,
    16: 128,
    17: 48,
    18: 560,
    19: 96,
    20: 64,
    21: 140,
    22: 0,
    23: 200,
    24: 128,
  },
  modLengthEmpty: 2108,
  shrink: { base: -396, codeRatio: 0.3649, impRatio: -0.0004 },
  fitted: true,
  fit: {
    meanErrUncompressed: 115,
    maxErrUncompressed: 729,
    meanErrShrinkled: 20,
    maxErrShrinkled: 57,
  },
};
