// Calibration table for the size estimator (TARGET: .bin code size).
//
// REGENERATED by the offline fitter (npm run fit:calibration, sizelab/fit/).
// The .bin is sub-additive (whole-program LTO + --gc-sections), so the HEADLINE
// uses an aggregate model fit on REAL patches; per-op opCost is a RELATIVE
// "which op is heavy" weight only and is NOT summed into codeBytes.
// Types live in ./calibration-types.
import type { CalibrationData } from './calibration-types';

export type { CalibrationData, FitQuality } from './calibration-types';

export const CALIBRATION: CalibrationData = {
  base: 0,
  perDistinctOp: 306,
  perSlot: 52,
  floor: 272,
  opCost: {
    1: 88,
    2: 200,
    3: 183,
    4: 291,
    5: 202,
    6: 143,
    7: 287,
    8: 281,
    9: 96,
    10: 88,
    11: 200,
    12: 281,
    13: 1081,
    14: 35,
    15: 448,
    16: 286,
    17: 48,
    18: 560,
    19: 235,
    20: 64,
    21: 284,
    22: 0,
    23: 200,
    24: 128,
  },
  modLengthEmpty: 2108,
  fitted: true,
  fit: {
    meanErr: 2017,
    maxErr: 6784,
    meanPct: 17,
  },
};
