// Calibration table for the size estimator (TARGET: .bin code size).
//
// REGENERATED by the offline fitter (npm run fit:calibration, sizelab/fit/).
// Additive per-op model fit UNWEIGHTED on synthetic + real .bin sizes; per-op
// opRoutine costs are "effective" (they absorb the .bin's mild sub-additivity)
// and SUM, with perSlot/perVarOperand, to the headline. Types: ./calibration-types.
import type { CalibrationData } from './calibration-types';

export type { CalibrationData, FitQuality } from './calibration-types';

export const CALIBRATION: CalibrationData = {
  base: 133,
  perSlot: 10,
  perVarOperand: 130,
  floor: 272,
  opRoutine: {
    1: 0,
    2: 194,
    3: 82,
    4: 97,
    5: 266,
    6: 0,
    7: 523,
    8: 263,
    9: 184,
    10: 176,
    11: 425,
    12: 340,
    13: 897,
    14: 168,
    15: 503,
    16: 0,
    17: 1504,
    18: 0,
    19: 1374,
    20: 2746,
    21: 859,
    22: 1504,
    23: 265,
    24: 128,
  },
  modLengthEmpty: 2108,
  fitted: true,
  fit: {
    meanErr: 1148,
    maxErr: 3996,
    meanPct: 10,
  },
};
