// Offline fitter: read corpus measurements.csv and regenerate
// src/sizecalc/calibration-data.ts. TARGET = the relocatable .bin code blob
// (what you embed in a demo), NOT the standalone exe.
//
// The .bin is strongly SUB-ADDITIVE: whole-program LTO + --gc-sections share
// helpers and collapse similar slots, so a non-negative per-op sum over-predicts
// real patches by 60%+. So we fit TWO things:
//
//   1. HEADLINE (aggregate): binBytes ≈ base + perDistinctOp·distinctOpTypes
//      + perSlot·nSlots, fit on REAL multi-instrument patches (weighted heavily).
//      This is the number shown to the user (~±20%).
//   2. RELATIVE per-op weights: a per-op ridge on the SYNTHETIC single-op corpus,
//      clamped ≥0. Only used to rank "which op is heavy" in the breakdown — it is
//      NOT summed into the headline.
//
// Pure CSV math — no wine. Run: npm run fit:calibration
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { OP_DEFS } from '../../src/schema/op-metadata';
import { parseCsv, type MeasurementRow } from '../corpus/measurements-csv';
import { ridgeFit, residuals } from './lstsq';

const SINE = 4;
const MOD_LENGTH_EMPTY = 2108; // chip term (resident mod template); not part of code
const REAL_WEIGHT = 8; // real patches drive the aggregate; synthetic shapes per-op

// Fallback per-op RELATIVE weights for ops the corpus doesn't exercise.
const SEED: Record<number, number> = {
  1: 48, 2: 64, 3: 80, 4: 128, 5: 80, 6: 80, 7: 112, 8: 120, 9: 32, 10: 32,
  11: 112, 12: 160, 13: 320, 14: 32, 15: 320, 16: 128, 17: 48, 18: 560, 19: 96,
  20: 64, 21: 140, 22: 0, 23: 200, 24: 128,
};

function opsPresent(r: MeasurementRow): Set<number> {
  const s = new Set<number>(r.measured.map((m) => m.op));
  if (r.producerCount > 0) s.add(SINE);
  return s;
}
const nSlots = (r: MeasurementRow): number => r.producerCount + r.measured.length;
const nDistinct = (r: MeasurementRow): number => opsPresent(r).size;
const c0 = (v: number): number => Math.max(0, Math.round(v));

function main(): void {
  const csv = readFileSync(join(import.meta.dirname, '..', 'corpus', 'measurements.csv'), 'utf8');
  const rows = parseCsv(csv);
  const reals = rows.filter((r) => r.id.startsWith('real:'));
  const synth = rows.filter((r) => !r.id.startsWith('real:'));

  // ── 1. Aggregate headline model: [1, distinctOpTypes, nSlots], reals weighted.
  const aggX: number[][] = [];
  const aggY: number[] = [];
  for (const r of rows) {
    const reps = r.id.startsWith('real:') ? REAL_WEIGHT : 1;
    for (let k = 0; k < reps; k++) { aggX.push([1, nDistinct(r), nSlots(r)]); aggY.push(r.binBytes); }
  }
  const ab = ridgeFit(aggX, aggY, 0.5);
  const base = ab[0]!;
  const perDistinctOp = ab[1]!;
  const perSlot = ab[2]!;
  const aggPred = (r: MeasurementRow): number => base + perDistinctOp * nDistinct(r) + perSlot * nSlots(r);

  // Residual over REAL patches only — that's the accuracy users actually see.
  const res = residuals(reals.map((r) => r.binBytes), (i) => aggPred(reals[i]!));
  const avgReal = reals.reduce((s, r) => s + r.binBytes, 0) / Math.max(1, reals.length);
  const floor = Math.min(...synth.map((r) => r.binBytes)); // empty/smallest .bin

  // ── 2. Per-op RELATIVE weights: per-op ridge on synthetic single-op rows only.
  const ops = [...new Set(synth.flatMap((r) => [...opsPresent(r)]))].sort((a, b) => a - b);
  const opX = synth.map((r) => {
    const present = opsPresent(r);
    return [1, ...ops.map((op) => (present.has(op) ? 1 : 0))];
  });
  const ob = ridgeFit(opX, synth.map((r) => r.binBytes), 0.5);
  const opFit = new Map<number, number>();
  ops.forEach((op, i) => opFit.set(op, ob[i + 1]!));

  const opCostEntries = OP_DEFS.map((d) => d.code).sort((a, b) => a - b)
    .map((code) => `    ${code}: ${opFit.has(code) ? c0(opFit.get(code)!) : (SEED[code] ?? 128)},`)
    .join('\n');

  const file = `// Calibration table for the size estimator (TARGET: .bin code size).
//
// REGENERATED by the offline fitter (npm run fit:calibration, sizelab/fit/).
// The .bin is sub-additive (whole-program LTO + --gc-sections), so the HEADLINE
// uses an aggregate model fit on REAL patches; per-op opCost is a RELATIVE
// "which op is heavy" weight only and is NOT summed into codeBytes.
// Types live in ./calibration-types.
import type { CalibrationData } from './calibration-types';

export type { CalibrationData, FitQuality } from './calibration-types';

export const CALIBRATION: CalibrationData = {
  base: ${c0(base)},
  perDistinctOp: ${c0(perDistinctOp)},
  perSlot: ${c0(perSlot)},
  floor: ${c0(floor)},
  opCost: {
${opCostEntries}
  },
  modLengthEmpty: ${MOD_LENGTH_EMPTY},
  fitted: true,
  fit: {
    meanErr: ${Math.round(res.mean)},
    maxErr: ${Math.round(res.max)},
    meanPct: ${Math.round((res.mean / avgReal) * 100)},
  },
};
`;
  writeFileSync(join(import.meta.dirname, '..', '..', 'src', 'sizecalc', 'calibration-data.ts'), file);

  console.log(`aggregate .bin headline (reals ×${REAL_WEIGHT}, ${reals.length} real / ${synth.length} synth):`);
  console.log(`  base=${c0(base)}  perDistinctOp=${c0(perDistinctOp)}  perSlot=${c0(perSlot)}  floor=${c0(floor)}`);
  console.log(`  REAL-patch residual: mean ${Math.round(res.mean)} (${Math.round((res.mean / avgReal) * 100)}% of avg ${Math.round(avgReal)}), max ${Math.round(res.max)} B`);
  const show = [2, 4, 7, 8, 13, 15, 16].filter((o) => opFit.has(o));
  console.log('  relative opCost: ' + show.map((o) => `${o}=${c0(opFit.get(o)!)}`).join(' '));
}

main();
