// Offline fitter (HYBRID): fit base + slotStreamCost + Shrinkler ratios from the
// corpus, but keep the source-grounded tiered per-op opCost seeds — because the
// single-phase-per-op corpus can't separate per-op routine from base/slot cost
// (collinear), so a raw per-op regression is degenerate. Totals + compression
// are measured; per-op stays the sensible relative ordering.
//
// Pure CSV math — no wine. Run: npm run fit:calibration
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { OP_DEFS } from '../../src/schema/op-metadata';
import { parseCsv, type MeasurementRow } from '../corpus/measurements-csv';
import { ridgeFit, residuals } from './lstsq';

const SINE = 4;
const MOD_LENGTH_EMPTY = 2108; // our minimal embedded mod (chip term; not fit here)

// Source-grounded per-op uncompressed code-size seeds (see calibration-data history).
const SEED: Record<number, number> = {
  1: 48, 2: 64, 3: 80, 4: 128, 5: 80, 6: 80, 7: 112, 8: 120, 9: 32, 10: 32,
  11: 112, 12: 160, 13: 320, 14: 32, 15: 320, 16: 128, 17: 48, 18: 560, 19: 96,
  20: 64, 21: 140, 22: 0, 23: 200, 24: 128,
};

function opsPresent(r: MeasurementRow): Set<number> {
  const s = new Set<number>(r.measured.map((m) => m.op));
  if (r.producerCount > 0) s.add(SINE);
  return s;
}
const nSlots = (r: MeasurementRow): number => r.producerCount + r.measured.length;
const seedSum = (r: MeasurementRow): number => [...opsPresent(r)].reduce((s, op) => s + (SEED[op] ?? 128), 0);

function main(): void {
  const csv = readFileSync(join(import.meta.dirname, '..', 'corpus', 'measurements.csv'), 'utf8');
  const rows = parseCsv(csv);

  // ── Fit base + slotStreamCost (opCost fixed to seeds; imports add 1:1) ──
  // y - Σseed_opCost = base + slotStreamCost·nSlots
  const fitRows = rows.filter((r) => r.importBytes === 0);
  const X = fitRows.map((r) => [1, nSlots(r)]);
  const yU = fitRows.map((r) => r.uncompressed - seedSum(r));
  const [base, slotStreamCost] = ridgeFit(X, yU, 1e-3) as [number, number];

  const predU = (r: MeasurementRow): number => base + slotStreamCost * nSlots(r) + seedSum(r) + r.importBytes;
  const resU = residuals(rows.map((r) => r.uncompressed), (i) => predU(rows[i]!));

  // ── Shrinkler: shrinkled = sBase + codeRatio·(uncompressed−imp) + impRatio·imp ──
  const Xs = rows.map((r) => [1, r.uncompressed - r.importBytes, r.importBytes]);
  const yS = rows.map((r) => r.shrinkled);
  const [sBase, codeRatio, impRatio] = ridgeFit(Xs, yS, 1e-6) as [number, number, number];
  const predS = (r: MeasurementRow): number => sBase + codeRatio * (r.uncompressed - r.importBytes) + impRatio * r.importBytes;
  const resS = residuals(rows.map((r) => r.shrinkled), (i) => predS(rows[i]!));

  const r0 = (n: number): number => Math.max(0, Math.round(n));
  const opCostEntries = OP_DEFS.map((d) => d.code).sort((a, b) => a - b)
    .map((code) => `    ${code}: ${SEED[code] ?? 128},`)
    .join('\n');

  const file = `// Calibration table for the size estimator.
//
// REGENERATED by the offline fitter (npm run fit:calibration, sizelab/fit/).
// HYBRID fit: base, slotStreamCost and the Shrinkler ratios are MEASURED from
// the corpus; per-op opCost keeps the source-grounded tiered seeds (the corpus
// can't separate per-op routine from base — collinear — so a raw per-op
// regression is degenerate). Types live in ./calibration-types.
import type { CalibrationData } from './calibration-types';

export type { CalibrationData, ShrinkModel, FitQuality } from './calibration-types';

export const CALIBRATION: CalibrationData = {
  base: ${r0(base)},
  slotStreamCost: ${r0(slotStreamCost)},
  opCost: {
${opCostEntries}
  },
  modLengthEmpty: ${MOD_LENGTH_EMPTY},
  shrink: { base: ${Math.round(sBase)}, codeRatio: ${codeRatio.toFixed(4)}, impRatio: ${impRatio.toFixed(4)} },
  fitted: true,
  fit: {
    meanErrUncompressed: ${Math.round(resU.mean)},
    maxErrUncompressed: ${Math.round(resU.max)},
    meanErrShrinkled: ${Math.round(resS.mean)},
    maxErrShrinkled: ${Math.round(resS.max)},
  },
};
`;
  writeFileSync(join(import.meta.dirname, '..', '..', 'src', 'sizecalc', 'calibration-data.ts'), file);

  console.log(`hybrid fit over ${rows.length} rows (${fitRows.length} import-free):`);
  console.log(`  base=${r0(base)}  slotStreamCost=${r0(slotStreamCost)}  (opCost = tiered seeds)`);
  console.log(`  uncompressed residual: mean ${Math.round(resU.mean)}, max ${Math.round(resU.max)} bytes`);
  console.log(`  shrink: base=${Math.round(sBase)} codeRatio=${codeRatio.toFixed(4)} impRatio=${impRatio.toFixed(4)}`);
  console.log(`  shrinkled residual: mean ${Math.round(resS.mean)}, max ${Math.round(resS.max)} bytes`);
}

main();
