// Offline fitter: read corpus measurements.csv and regenerate
// src/sizecalc/calibration-data.ts. TARGET = the relocatable .bin code blob.
//
// Model (additive per-op, fit UNWEIGHTED on synthetic + real rows):
//   binBytes ≈ base + Σ_distinct opRoutine[op] + perSlot·nSlots
//                   + perVarOperand·nVarOperands
//
// Unweighted is the key: an earlier version weighted the real patches ×8, which
// drove the base negative and inflated per-op costs (making the additive model
// look hopeless). Fit unweighted, the per-op routine costs settle to "effective"
// values that absorb the .bin's mild sub-additivity, and the model lands ~10%
// mean on real patches — better than the old aggregate, and coherent (per-op
// figures sum to the headline).
//
// Pure CSV math — except real-patch operand modes, which we recompute from the
// .akp files. Run: npm run fit:calibration
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { OP_DEFS, opByCode } from '../../src/schema/op-metadata';
import { parseAkp } from '../../src/fileio/akp';
import type { Slot } from '../../src/patch/types';
import { parseCsv, type MeasurementRow } from '../corpus/measurements-csv';
import { ridgeFit, residuals } from './lstsq';

const SINE = 4;
const MOD_LENGTH_EMPTY = 2108; // chip term (resident mod template); not part of code
const PATCHES = join(import.meta.dirname, '..', '..', '..', 'patches');

// Fallback routine cost for ops the corpus doesn't exercise (clone/loop_gen/etc.).
const SEED: Record<number, number> = {
  17: 120, 18: 560, 20: 64, 22: 0, 23: 200, 24: 128,
};

function opsPresent(r: MeasurementRow): Set<number> {
  const s = new Set<number>(r.measured.map((m) => m.op));
  if (r.producerCount > 0) s.add(SINE);
  return s;
}
const nSlots = (r: MeasurementRow): number => r.producerCount + r.measured.length;

/** Variable (non-const) var-or-const operands set on an op slot. */
export function slotVarOperands(s: Slot): number {
  const def = opByCode(s.fn);
  if (!def) return 0;
  let n = 0;
  for (const p of def.params) {
    if (p.type.kind === 'var-or-const' && p.selector && (s[p.selector] as number) !== 0) n++;
  }
  return n;
}

/** # variable operands across a row: from mode strings (synth) or .akp (real). */
function nVarOperands(r: MeasurementRow): number {
  if (r.id.startsWith('real:')) {
    const patch = parseAkp(new Uint8Array(readFileSync(join(PATCHES, r.id.slice(5) + '.akp'))));
    let nv = 0;
    for (const ins of patch.instruments) for (const s of ins.slots) if (s.fn !== 0) nv += slotVarOperands(s);
    return nv;
  }
  return r.measured.reduce((n, m) => n + (m.mode.match(/V/g)?.length ?? 0), 0);
}

const c0 = (v: number): number => Math.max(0, Math.round(v));

function main(): void {
  const csv = readFileSync(join(import.meta.dirname, '..', 'corpus', 'measurements.csv'), 'utf8');
  const rows = parseCsv(csv).filter((r) => r.binBytes > 0); // drop unmeasured rows
  const reals = rows.filter((r) => r.id.startsWith('real:'));

  // Features: [1, op-indicators…, nSlots, nVarOperands]. Fit UNWEIGHTED.
  const ops = [...new Set(rows.flatMap((r) => [...opsPresent(r)]))].sort((a, b) => a - b);
  const feat = (r: MeasurementRow): number[] => {
    const pres = opsPresent(r);
    return [1, ...ops.map((o) => (pres.has(o) ? 1 : 0)), nSlots(r), nVarOperands(r)];
  };
  const X = rows.map(feat);
  const y = rows.map((r) => r.binBytes);
  const beta = ridgeFit(X, y, 0.5);
  const base = beta[0]!;
  const perSlot = beta[beta.length - 2]!;
  const perVarOperand = beta[beta.length - 1]!;
  const routine = new Map<number, number>();
  ops.forEach((o, i) => routine.set(o, beta[i + 1]!));

  const pred = (r: MeasurementRow): number => {
    let v = base + perSlot * nSlots(r) + perVarOperand * nVarOperands(r);
    for (const o of opsPresent(r)) v += routine.get(o) ?? 0;
    return v;
  };
  const res = residuals(reals.map((r) => r.binBytes), (i) => pred(reals[i]!));
  const avgReal = reals.reduce((s, r) => s + r.binBytes, 0) / Math.max(1, reals.length);
  const floor = Math.min(...rows.map((r) => r.binBytes));

  const routineEntries = OP_DEFS.map((d) => d.code).sort((a, b) => a - b)
    .map((code) => `    ${code}: ${routine.has(code) ? c0(routine.get(code)!) : (SEED[code] ?? 128)},`)
    .join('\n');

  const file = `// Calibration table for the size estimator (TARGET: .bin code size).
//
// REGENERATED by the offline fitter (npm run fit:calibration, sizelab/fit/).
// Additive per-op model fit UNWEIGHTED on synthetic + real .bin sizes; per-op
// opRoutine costs are "effective" (they absorb the .bin's mild sub-additivity)
// and SUM, with perSlot/perVarOperand, to the headline. Types: ./calibration-types.
import type { CalibrationData } from './calibration-types';

export type { CalibrationData, FitQuality } from './calibration-types';

export const CALIBRATION: CalibrationData = {
  base: ${c0(base)},
  perSlot: ${c0(perSlot)},
  perVarOperand: ${c0(perVarOperand)},
  floor: ${c0(floor)},
  opRoutine: {
${routineEntries}
  },
  modLengthEmpty: ${MOD_LENGTH_EMPTY},
  fitted: true,
  fit: {
    meanErr: ${Math.round(res.mean)},
    maxErr: ${Math.round(res.max)},
    meanPct: ${Math.round((res.mean / avgReal) * 100)},
  },
};
`;
  writeFileSync(join(import.meta.dirname, '..', '..', 'src', 'sizecalc', 'calibration-data.ts'), file);

  console.log(`additive per-op fit (${rows.length} rows, unweighted, ${reals.length} real):`);
  console.log(`  base=${c0(base)} perSlot=${c0(perSlot)} perVarOperand=${c0(perVarOperand)} floor=${c0(floor)}`);
  console.log(`  REAL residual: mean ${Math.round(res.mean)} (${Math.round((res.mean / avgReal) * 100)}%) max ${Math.round(res.max)} B`);
  const show = [2, 4, 7, 13, 15, 16].filter((o) => routine.has(o));
  console.log('  opRoutine: ' + show.map((o) => `${o}=${c0(routine.get(o)!)}`).join(' '));
}

main();
